### ISSUE TITLE
Marshalling Attributes from derived class are not taken into account

### ISSUE THREAD

**Issue by stephanewierzbicki** [onryldz/x-superobject#100]
Hello,

Marshalling Attributes from derived class are not taken into account.
For exemple : 

```
TMyObject = class
Public
  Name : string;
  [DISABLE]
  Id : integer;
End;

TMyNewObject = class(TMyObject )
Public
  Street: string;
End;
```

TMyNewObject .AsJSON will display all fields.

**Comment by onryldz** [comment]
Hello, 
I did not occurred this problem. Which version of Delphi are you using? 

Also;
XSuperObject must be in uses list where you had declared that class (for alias, disable, etc.)
```pascal
uses
   .... XSuperObject .... ;
type
  TMyObject = class
Public
  Name : string;
  [DISABLE]
  Id : integer;
End;

TMyNewObject = class(TMyObject )
Public
  Street: string;
End;
....
```

**Comment by stephanewierzbicki** [comment]
I'm using Delphi Berlin

**Comment by barisatalay** [comment]
@stephanewierzbicki I was tested. 

http://i.hizliresim.com/kvPPEy.png
