### ISSUE TITLE
Is it possible to serialize class TCollection like TObjeclist ?

### ISSUE THREAD

**Issue by stephanewierzbicki** [onryldz/x-superobject#101]
Hello,

Is it possible to serialize TCollection class like a TObjeclist class ?
I'm asking this because there is garbage when serializing a TCollection class (capacity, count, published method properties...)

TIA

**Comment by vkrapotkin** [comment]
Of course.
This technique is universal.
We should make a fake array property for saving/loading

**Comment by stephanewierzbicki** [comment]
will be nice to have it :D
