### ISSUE TITLE
Handle Read only property fields when unmarshalling ?

### ISSUE THREAD

**Issue by stephanewierzbicki** [onryldz/x-superobject#108]
Hello,

I don't know if this is meaningful or not, but can your framework handle read only properties fields when unmarshalling a json string ?

I'm right now adding the [DISABLE] attribute 

Is there another way ?

**Comment by 113Bom** [comment]
Do you have a special need to handle properties?  Can't you not just set the Fields?
( Do you have some code that needs to run with the "setter", please explain if so)
My approach to "read only" properties are not to use properties at all. - Just set the objects state, by setting all Fields.  TSerializeParseOptions.Visibilities := [mvPrivate]

**Comment by 113Bom** [comment]
Perhaps this is what you want?   
[DISABLEWRITE ]
Below is code @ line 110 in XSuperObject.pas


`  DISABLEREAD = class(TCustomAttribute)
  end;

  DISABLEWRITE = class(TCustomAttribute)
  end;`
