### ISSUE TITLE
How to i can access to two parameters with one name and different types?

### ISSUE THREAD

**Issue by Ze2QvoQxxKeu** [onryldz/x-superobject#112]
Example:

    {
      "xxfile.txt": 666,
      "xxfile.txt": {
        
      }
    }

If i refer to "xxfile.txt" as object, then i get "invalid class typecast" exception

**Comment by vkrapotkin** [comment]
it's not a valid json

**Comment by Ze2QvoQxxKeu** [comment]
Big thanks. I think it's bug of xsuperobject...
Я думал что это баг, а это ограничения JSON
