### ISSUE TITLE
question: how to convert array of objects?

### ISSUE THREAD

**Issue by boomsya** [onryldz/x-superobject#116]
hi, i dont understand how to parse file like this:
JSN = '['+
  '{'+
    '"upd": 0,'+
    '"tag": 11,'+
    '"data": "Hazel Pratt",'+
    '"ecp": "Hazel Pratt"'+
  '},{'+
    '"upd": 0,'+
    '"tag": 11,'+
    '"data": "Hazel Pratt",'+
    '"ecp": "Hazel Pratt"'+
  '},{'+
    '"upd": 0,'+
    '"tag": 11,'+
    '"data": "Hazel Pratt",'+
    '"ecp": "Hazel Pratt"'+
  '}]';

problem in recognize root node:
```
var obj: ISuperObject;
    X: ISuperObject;
    J: Integer;
begin
X := TSuperObject.Create(JSN);
  with X.A[''] do    <----------- here
    for J := 0 to Length -1 do
    begin
      Obj := O[J];
      Obj.First;
      while not Obj.EoF do
      begin
         //...
         Obj.Next;
      end;
      //...
    end;
```

**Comment by boomsya** [comment]
i found simple solution:

```
 TCrdUpdate = record
    upd: integer;
    tag: integer;
    data: Ansistring;
    ecp: Ansistring;
  end;

  TArrCrdUpdate = array of TCrdUpdate;

var Parse:TArrCrdUpdate;
Parse := TJSON.Parse<TArrCrdUpdate>(JSN);
```

but in prior i want do that with TSuperObject

**Comment by vkrapotkin** [comment]
There's another simple case
arr:ISuperArray;

arr:=TSuperArray.Create(json)
