### ISSUE TITLE
how could i add to object without specified an integer

### ISSUE THREAD

**Issue by topkung1** [onryldz/x-superobject#117]
with X.A['adresses'].O[0] {Auto Create} do
  begin
    S['adress'] := 'blabla';
    S['city'] := 'Antalya';
    I['pc'] := 7160;
  end;

I want to add more items into addresses

How could I add into it without specified '[0]' this?

because i want to loop like for a in b or something thanks

**Comment by vkrapotkin** [comment]
you have to create an item,  then call add method
.....addresses.add(item)

**Comment by topkung1** [comment]
can you show me how to do it please below code isn't working

![image](https://user-images.githubusercontent.com/15030417/28810960-a695027e-76b6-11e7-88ce-8d47253019b8.png)

**Comment by topkung1** [comment]
[update] the above code is working fine thanks so much **vkrapotkin**
