### ISSUE TITLE
Question: Set DateFormat for deserialization?

### ISSUE THREAD

**Issue by boomsya** [onryldz/x-superobject#120]
hi
can i set DateFormat for Deserialization?
my datetime format in json is: `dd.mm.yyyy hh:nn:ss   (sample: 31.12.1980 12:38:59)`

when i call:
`obj.O['data'].D['reg_dt'];`

i have exception: 
`invalid typecast`

**Comment by boomsya** [comment]
at now i use this as solution:

```
fs := TFormatSettings.Create;
fs.ShortDateFormat := 'hh:nn:ss';
fs.ShortDateFormat := 'dd.mm.yyyy';

regdt := StrToDateTimeDef(Obj.O['data'].S['reg_dt'], 0, fs);
```

**Comment by onryldz** [comment]
see also
https://github.com/onryldz/x-superobject/blob/master/XSuperJSON.pas#L2349

**Comment by boomsya** [comment]
thanks

**Comment by onryldz** [comment]
you are welcome
