### ISSUE TITLE
Access violation on Finalization

### ISSUE THREAD

**Issue by littleearth** [onryldz/x-superobject#71]
The Destroy method in TJSONDateManager causes an AV on shutdown.

This resolves. Does the _release need to be there?
````objectpascal
class destructor TJSONDateManager.Destroy;
begin
  if Assigned(FFormats) then
  begin
    FreeAndNil(FFormats);
  end;
end;
````

**Comment by onryldz** [comment]
Which version, platform, etc. are you using? Can you give more details?

**Comment by littleearth** [comment]
Hi, XE8.1, I have only tested on Win32 and Win64
