### ISSUE TITLE
Delphi 10 [DCC Error] XSuperJSON.pas(2097): E2035 Not enough actual parameters

### ISSUE THREAD

**Issue by vkrapotkin** [onryldz/x-superobject#74]
class destructor TJSONDateManager.Destroy;
var
  I: Integer;
begin
  if Assigned(FFormats) then
  begin
    for I := 0 to FFormats.Count - 1 do
      FFormats[I]._Release; // error pointer is here before '.Release'
    FFormats.Free;
  end;
end;

**Comment by onryldz** [comment]
This issue is resolved. Please get the latest commit 1fa2028a335f8112b2bdb84a9c1888908d8e7dc4.

**Comment by vkrapotkin** [comment]
Oh! Very attractive!
Thanks a lot!

**Comment by djjd47130** [comment]
I have this error even with the latest source. Precisely the same thing.

**Comment by michaelpz** [comment]
I tested final version on Delphi 10 and we don't have any problem. maybe you have conflict with other libraries and definitions
