### ISSUE TITLE
Marshalling not working for properties in record

### ISSUE THREAD

**Issue by shahriar-b** [onryldz/x-superobject#76]
example: 
```pascal
type
 MyRecord = record
 [ALIAS('Type')]
 property typ : string read FType write FType;
....

```

If try to serialize Type from JSON it will not work for records but it works fine for Class.

**Comment by onryldz** [comment]
```pascal
uses
   .... XSuperObject .... ;
type
  MyRecord = record
      [ALIAS('Type')]
      typ: string;
....
```
Records support only field members, other words you have to use records with fields.
Note: XSuperObject must be in uses list where you had declared that record (for alias, etc.)
