### ISSUE TITLE
A memory block has been leaked

### ISSUE THREAD

**Issue by litewei** [onryldz/x-superobject#78]
When I debug a new project just with a blank window, this memory leak error occurs.

The program .pas codes are:

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs;

type
  TForm2 = class(TForm)
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  Form2: TForm2;

implementation
 uses XSuperJSON,XsuperObject;
{$R *.dfm}

end.

The MemoryManager_EventLog.txt reported by FastMM shows:

--------------------------------2015/10/24 0:41:05--------------------------------
A memory block has been leaked. The size is: 20

This block was allocated by thread 0x1F54, and the stack trace (return addresses) at the time was:
406A06 [System.pas][System][@GetMem$qqri][4391]
40781B [System.pas][System][TObject.NewInstance$qqrv][15641]
40CD55 [System.pas][System][TInterfacedObject.NewInstance$qqrv][36999]
407F76 [System.pas][System][@ClassCreate$qqrpvzc][16951]
407910 [System.pas][System][TObject.$bctr$qqrv][15705]
64A91E 
409020 [System.pas][System][InitUnits$qqrv][22225]
40908C [System.pas][System][@StartExe$qqrp23System.PackageInfoTablep17System.TLibModule][22297]
40E2EB [SysInit.pas][SysInit][@InitExe$qqrpv][1200]
64A98C 
7538337A [BaseThreadInitThunk]

The block is currently used for an object of class: XSuperJSON$152$ActRec

The allocation number is: 465

Current memory dump of 256 bytes starting at pointer address 7EF7F2F0:
BC 98 63 00 01 00 00 00 B8 21 40 00 30 98 63 00 00 00 00 00 8F 6D C0 08 00 00 00 00 11 02 F8 7E
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 E9 01 00 00 06 6A 40 00 4B 95 40 00 D8 99 40 00
F5 7B 63 00 43 7E 63 00 D7 7E 63 00 46 A9 64 00 20 90 40 00 8C 90 40 00 EB E2 40 00 8C A9 64 00
54 1F 00 00 54 1F 00 00 22 6A 40 00 05 96 40 00 25 AB 40 00 6D AA 40 00 B7 79 40 00 32 78 40 00
C1 7F 40 00 67 7C 63 00 3F 79 40 00 F4 8B 63 00 3F 79 40 00 14 00 00 00 B0 04 02 00 42 63 7D 85
90 A2 66 00 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 80 BD 9C 82 7A 00 00 00 00 71 06 F8 7E
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 30 03 00 00 75 6A 40 00 89 B4 40 00 C2 B5 40 00
EF C2 63 00 CF A9 64 00 36 93 0F 01 0C B6 63 00 8A B5 63 00 AB BA 63 00 3F 79 40 00 4B 7C 63 00
? ? c  .  .  .  .  .  ? !  @  .  0  ? c  .  .  .  .  .  ? m  ? .  .  .  .  .  .  .  ? ~
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ? .  .  .  .  j  @  .  K  ? @  .  ? ? @  .
? {  c  .  C  ~  c  .  ? ~  c  .  F  ? d  .     ? @  .  ? ? @  .  ? ? @  .  ? ? d  .
T  .  .  .  T  .  .  .  "  j  @  .  .  ? @  .  %  ? @  .  m  ? @  .  ? y  @  .  2  x  @  .
?   @  .  g  |  c  .  ?  y  @  .  ? ? c  .  ?  y  @  .  .  .  .  .  ? .  .  .  B  c  }  ?
? ? f  .  €  €  €  €  €  €  €  €  €  €  €  €  €  €  €  €  ? ? ? z  .  .  .  .  q  .  ? ~
.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  0  .  .  .  u  j  @  .  ? ? @  .  ? ? @  .
? ? c  .  ? ? d  .  6  ? .  .  .  ? c  .  ? ? c  .  ? ? c  .  ?  y  @  .  K  |  c  .

--------------------------------2015/10/24 0:41:05--------------------------------
This application has leaked memory. The small block leaks are (excluding expected leaks registered by pointer):

13 - 20 bytes: XSuperJSON$152$ActRec x 1

Note: Memory leak detail is logged to a text file in the same folder as this application. To disable this memory leak check, undefine "EnableMemoryLeakReporting".

**Comment by litewei** [comment]
I tried with XE7 and VCL windows.

**Comment by kapytanhook** [comment]
Same here, XE7 memory leak.
It seems related to XSuperJSON line 2279
TJSONDateManager.Formats.Add(...);

If I comment it it out, I dont get the leak. personally I dont use any dates so I just commented it out.
