### ISSUE TITLE
Escapes

### ISSUE THREAD

**Issue by eduardoelias** [onryldz/x-superobject#90]
Great work, I am using this library for years now and is very good.

There is a problem, this JSON:

{\"base\":2,\"dominio\":[3,4,5,6,7,9,11,12,13,14,15,16,17,18,19,20,21,22,23,999,1000,1100]}

Causes problem when parsing. Reading the documentation in Json.Org, the parser should understand the escapes (they are few) and translate correctly. But in this case it is stoping in the first escape.

Using latest version with Seattle win32

**Comment by onryldz** [comment]
Hi Eduardo,
You can use  Escape just in string, you have to use  "\"Base\""
