### ISSUE TITLE
Cannot create an TSuperObject with string field containing a linefeed/linebreak

### ISSUE THREAD

**Issue by stephanewierzbicki** [onryldz/x-superobject#91]
Hello,
I'm getting an exception when using line linefeed/linebreak in my JSON string :
TSuperObject.Create('{"adress"="My Adress'+#13#10+'My City"}');

Is it possible to dynamically replace such special char with escape sequences ?

legitimate escape sequences within a JSON string:
    \"
    \\
    \/
    \b
    \f
    \n
    \r
    \t
    \u followed by four-hex-digits

**Comment by stephanewierzbicki** [comment]
Hello Onur,

Thank you for your commit. I've tested my code (using CreateWithEscape) and I'm getting this exception :

Exception 'first chance' à $7517DAD8. exception class TJSONSyntaxError with message 'Unexpected token ILLEGAL. (Line: 0 Col: 9)'. Process CRM.exe (416)

**Comment by onryldz** [comment]
Hi Stephane, 
You have to use '=' instead of ':' for json field operator.

As a sample:
TSuperObject.CreateWithEscape('{"adress":"My Adress'+#13#10+'My City"}');

**Comment by stephanewierzbicki** [comment]
I'm a noob...

Can you test this JSON string ? (please use Formated.txt file) :

Procedure Load;
var X: ISuperObject;
    SL:TStringlist;
begin
   sl := TStringlist.create;
     try
      sl.LoadFromFile('D:\Formated.txt')  ;
      X:= TSuperObject.CreateWithEscape(sl.Text);
     finally
       sl.free;
     end;
end;

[Formated.txt](https://github.com/onryldz/x-superobject/files/231844/Formated.txt)
