### ISSUE TITLE
Are the links to indy and DB really needed ?

### ISSUE THREAD

**Issue by vkrapotkin** [onryldz/x-superobject#92]
in XuperObject.pas we have

```
uses Classes,  Variants,   SysUtils,   Character,   XSuperJSON,   RTTI,   TypInfo,   DB,
  Generics.Collections,   IdGlobal,   IdCoderMIME;

```
can we avoid of using indy and DB modules to reduce unneedable linkage ?

**Comment by onryldz** [comment]
Hi Vladimir,
Nowadasy, I'm so busy. But, it seems possible.

**Comment by vkrapotkin** [comment]
Thank you for your great work. But let's return to the issue.
Now XS needs indy only to do a Base64 encoding.
Since XE7 we have native methods to do it:
TNetEncoding.Base64.EncodeBytesToString(TBytes):string;
TNetEncoding.Base64.DecodeStringToBytes(string):TBytes;
I guess it's much better to use it.
After that we no more need have to define SP_STREAM
