### ISSUE TITLE
Multi thread

### ISSUE THREAD

**Issue by vianney-allaire** [onryldz/x-superobject#93]
Hello, 
me and my superior disagree on one point. He says that x-superobject is NOT multithread ..... Or rather "thread safe". I use and like this library a lot, and he wants to replace it with the Delphi xe7 Json tools. I looke everywhere on the net for an answer, but found nothing. 
Is XSuperObject really not thread safe ? Thank you for your response.

**Comment by vkrapotkin** [comment]
I use it in multithreading apps
Flight is normal

**Comment by onryldz** [comment]
Super Object already supports the multithreading apps.
Sample: 
var
  I: Integer;
const
  JSON = '{ "o": { '+
         '    "1234567890": {'+
         '    "last use date": "2010-10-17T01:23:20",'+
         '    "create date": "2010-10-17T01:23:20",'+
         '    "name": "iPhone 8s"'+
         '        }'+
         '  },'+
         '  "Index": 0, '+
         '  "Data": {"Index2": 1}, '+
         '  "a": [{'+
         '    "last use date": "2010-10-17T01:23:20",'+
         '    "create date": "2010-11-17T01:23:20",'+
         '    "name": "iPhone 8s",'+
         '    "arr": [1,2,3] '+
         '  }, '+
         '  {'+
         '    message: "hello"'+
         '  }]'+
         '}';
begin
  for I := 0 to 100 do
      TThread.CreateAnonymousThread(procedure
      var
        X: ISuperObject;
      begin
        X := SO(JSON);
      end).Start;
end;

**Comment by vianney-allaire** [comment]
Thank you very much for your response.

Vianney

2016-04-28 13:18 GMT+02:00 Onur YILDIZ <notifications@github.com>:
