### ISSUE TITLE
Unknown identifier

### ISSUE THREAD

**Issue by rbrose** [onryldz/x-superobject#97]
Hi,

i have no idea why i get this error shown in RAD "Unknown identifier" if i use:
  currentObj: ISuperObject;
  enum: TSuperEnumerator<IJSONAncestor>

 enum:=currentObj.AsArray.GetEnumerator;  <------ Here i get a error.

But if i execute the app all works fine. How i can fix it that IDE don't show error?

![bildschirmfoto 2016-06-16 um 21 39 05](https://cloud.githubusercontent.com/assets/1026824/16130730/c886c010-340a-11e6-9c8b-9cacd8db288d.png)
![bildschirmfoto 2016-06-16 um 21 38 55](https://cloud.githubusercontent.com/assets/1026824/16130731/c887d2e8-340a-11e6-9332-72e34da0bd3c.png)

**Comment by vkrapotkin** [comment]
The best way to correct this in modern Delphi is
Tools -- Options -- Editor Options -- Code Insight  
Turn OFF **Error Insight** checkbox

**Comment by rbrose** [comment]
But then i get no marked all errors :-)

Why RAD mark this as error?

**Comment by vkrapotkin** [comment]
Because the author of error insight fired just after making of it
EI has been made in discontinued .net and now it's just "error inside" )))
