### ISSUE TITLE
An empty JSON TDateTime value will abort marshalling

### ISSUE THREAD

**Issue by stephanewierzbicki** [onryldz/x-superobject#98]
Hello,

An empty JSON TDateTime value will abort marshalling

```
TMyObject = class
MyDate:TDateTime
end;
```

For exemple, this will failed :
`MyObject := TMyObject.FromJSON('{"MyDate":""}');`

Would you mind to update 

class procedure TSerializeParse.WriteMember<T, Typ>(Data: Pointer; Member: Typ;
  RType: PTypeInfo; MemberValue: TRttiObject; IJsonData: IBaseJSON<T, Typ>);

and add extra check for TDatetime types :

from

```
  if (RType = TypeInfo(TDateTime)) or (RType = TypeInfo(TDate)) or (RType = TypeInfo(TTime)) then
  begin
    if (IJSONData.Ancestor[Member].DataType <> dtNull)  then
       SetValue<Typ>(Data, MemberValue, Member, TValue.From<TDateTime>(IJSONData.Ancestor[Member].AsVariant))
  end
  else
```

to

```
  if (RType = TypeInfo(TDateTime)) or (RType = TypeInfo(TDate)) or (RType = TypeInfo(TTime)) then
  begin
    if (IJSONData.Ancestor[Member].DataType <> dtNull)
//     and TJSONDateManager.Check(IJSONData.Ancestor[Member].AsVariant, dT, ValType )
    then
       SetValue<Typ>(Data, MemberValue, Member, TValue.From<TDateTime>(IJSONData.Ancestor[Member].AsVariant))
  end
  else
```

**Comment by vkrapotkin** [comment]
IMHO empty date should be written as null.
Or not?
More of this - how can I determine that "MyDate":"" is a DateTime field ? It looks like just an empty string.

**Comment by stephanewierzbicki** [comment]
JSON dates are stored in string and there is no rules about formatting them.
Risk is hight that you will consume a badly formatted date. I see no reason why all marshalling should be aborted on such case. 

XSuperObject use RTTI to determine the data type kind of the JSON value. In my exemple, MyDate is declared as a TDateTime. 

As TDatetime is an alias to Double, it is impossible to set it to null, rather 0.

**Comment by stephanewierzbicki** [comment]
@vkrapotkin what do you think about my request ?
